#!/bin/bash

CURRENTDIR=$(pwd)
DESTINATIONBIN="/usr/local/bin/"
DESTINATIONMAN="/usr/share/man/man1/"
FILEBIN="nsaflood"
FILESCHED="nsaf-sched"
FILEMAN="nsaflood.1.gz"
FILEMANSRC="nsaflood.1"
FILESCHEDMAN="nsaf-sched.1.gz"
FILESCHEDMANSRC="nsaf-sched.1"
CONFIGDIR="/etc/nsaflood"
CONFIGFILE="nsaflood.conf"
CONFIGPEERTAB="peertab"

if [ $UID != 0 ]; then

  echo "Only root can install programs.
Exiting..."

	exit 1
fi

echo -n "Moving $FILEBIN to $DESTINATIONBIN...				"

cp $CURRENTDIR/$FILEBIN $DESTINATIONBIN

if [ $? -ne 0 ]; then

	echo -e "\E[31m[FAILURE!]\E[37m
ERROR: Could not copy $FILEBIN to $DESTINATIONBIN
This may be due to insufficient file permissions, or the partition being full.
Exiting..."

	exit 2
fi

echo -ne "\E[32m[success!]\E[37m
Updating file ownership and permissions on $FILEBIN...		"

chown 0:0 $DESTINATIONBIN/$FILEBIN
chmod 755 $DESTINATIONBIN/$FILEBIN

echo -ne "\E[32m[success!]\E[37m
Moving $FILESCHED to $DESTINATIONBIN...				"

cp $CURRENTDIR/$FILESCHED $DESTINATIONBIN

if [ $? -ne 0 ]; then

	echo -e "\E[31m[FAILURE!]\E[37m
ERROR: Could not copy $FILESCHED to $DESTINATOINBIN
This may be due to insufficent file permissions, or the partition being full.
Exiting..."

	exit 2
fi

echo -ne "\E[32m[success!]\E[37m
Updating file ownership and permissions on $FILESCHED...	"

chown 0:0 $DESTINATIONBIN/$FILESCHED
chmod 755 $DESTINATIONBIN/$FILESCHED

echo -ne "\E[32m[success!]\E[37m
Compressing $FILEMANSRC and moving to $DESTINATIONMAN...	"

gzip --stdout $CURRENTDIR/$FILEMANSRC > $DESTINATIONMAN/$FILEMAN

if [ $? -ne 0 ]; then

	echo -e "\E[31m[FAILURE!]\E[37m
ERROR: Could not copy $FILEMAN to $DESTINATIONMAN
This may be due to insuffiencet file permissions, or the partition being full.
Exiting..."

	exit 2
fi

echo -ne "\E[32m[success!]\E[37m
Updating file ownership and permissions of $FILEMAN...	"

chown 0:0 $DESTINATIONMAN/$FILEMAN
chmod 744 $DESTINATIONMAN/$FILEMAN

echo -ne "\E[32m[success!]\E[37m
Compressing $FILESCHEDMANSRC and moving to $DESTINATIONMAN...	"


gzip --stdout $CURRENTDIR/$FILESCHEDMANSRC > $DESTINATIONMAN/$FILESCHEDMAN

if [ $? -ne 0 ]; then

	echo -e "\E[31m[FAILURE!]\E[37m
ERROR: Could not copy $FILESCHEDMAN to $DESTINATIONMAN
This may be due to insufficient file permissions, or the partition being full.
Exiting..."

	exit 2
fi

echo -ne "\E[32m[success!]\E[37m
Updating file ownership and permissions of $FILESCHEDMAN...	"

chown 0:0 $DESTINATIONMAN/$FILESCHEDMAN
chmod 744 $DESTINATIONMAN/$FILESCHEDMAN

echo -ne "\E[32m[success!]\E[37m
Creating $CONFIGDIR...					"

mkdir $CONFIGDIR > /dev/null 2>&1

if [ $? -ne 0 ]; then
	echo -e "\E[31m[FAILURE!]\E[37m
ERROR: Could not create directory $CONFIGDIR
This may be due to insufficient file permissions, or the directory exists.
Exiting..."
	exit 2
fi

echo -ne "\E[32m[success!]\E[37m
Creating configuration files...					"

cp $CONFIGFILE $CONFIGDIR/$CONFIGFILE

if [ $? -ne 0 ]; then
	echo -e "\E[31m[FAILURE!]\E[37m
ERROR: Could not create file $CONFIGFILE
This may be due to insufficient file permissions.
Exiting..."
	exit 2
fi

touch $CONFIGDIR/$CONFIGPEERTAB

if [ $? -ne 0 ]; then
	echo -e "\E[31m[FAILURE!]\E[37m
ERROR: Could not create file $CONFIGFILE
This may be due to insufficient file permissions.
Exiting..."
	exit 2
fi

echo -e "\E[32m[success!]\E[37m
Installation of NSAFlood finished successfully."

exit 0
