#!/bin/bash

CURRENTDIR=$(pwd)
DESTINATIONBIN="/usr/local/bin/"
DESTINATIONMAN="/usr/share/man/man1/"
FILEBIN="nsaflood"
FILESCHED="nsaf-sched"
FILEMAN="nsaflood.1.gz"
FILEMANSRC="nsaflood.1"
FILESCHEDMAN="nsaf-sched.1.gz"
FILESCHEDMANSRC="nsaf-sched.1"

if [ $UID != 0 ]; then

  echo -ne " Only root can install programs.\n"\
	"Exiting...\n"

	exit 1
fi

echo -ne "\n Moving $FILEBIN to $DESTINATIONBIN..."

cp $CURRENTDIR/$FILEBIN $DESTINATIONBIN

if [ $? -ne 0 ]; then

	echo -ne " ERROR: Could not copy $FILEBIN to $DESTINATIONBIN\n"\
	"This may be due to insufficient file permissions, or the partition being full.\n"\
	"Exiting...\n"

	exit 2
fi

echo -ne " success!\n"\
" Updating file ownership and permissions on $FILEBIN..."

chown 0:0 $DESTINATIONBIN/$FILEBIN
chmod 755 $DESTINATIONBIN/$FILEBIN

echo -ne " succes!\n\n"\
" Moving $FILESCHED to $DESTINATIONBIN..."

cp $CURRENTDIR/$FILESCHED $DESTINATIONBIN

if [ $? -ne 0 ]; then

	echo -ne "ERROR: Could not copy $FILESCHED to $DESTINATOINBIN\n"\
	" This may be due to insufficent file permissions, or the partition being full.\n"\
	" Exiting...\n"

	exit 2
fi

echo -ne " success!\n"\
" Updating file ownership and permissions on $FILESCHED..."

chown 0:0 $DESTINATIONBIN/$FILESCHED
chmod 755 $DESTINATIONBIN/$FILESCHED

echo -ne " success!\n\n"\
" Compressing $FILEMANSRC and moving to $DESTINATIONMAN..."

gzip --stdout $CURRENTDIR/$FILEMANSRC > $DESTINATIONMAN/$FILEMAN

if [ $? -ne 0 ]; then

	echo -ne " ERROR: Could not copy $FILEMAN to $DESTINATIONMAN\n"\
	"This may be due to insuffiencet file permissions, or the partition being full.\n"\
	"Exiting...\n"

	exit 2
fi

echo -ne " success!\n"\
" Updating file ownership and permissions of $FILEMAN..."

chown 0:0 $DESTINATIONMAN/$FILEMAN
chmod 744 $DESTINATIONMAN/$FILEMAN

echo -ne " success!\n\n"\
" Compressing $FILESCHEDMANSRC and moving to $DESTINATIONMAN..."


gzip --stdout $CURRENTDIR/$FILESCHEDMANSRC > $DESTINATIONMAN/$FILESCHEDMAN

if [ $? -ne 0 ]; then

	echo one " ERROR: Could not copy $FILESCHEDMAN to $DESTINATIONMAN\n"\
	"This may be due to insufficient file permissions, or the partition being full."\
	"Exiting...\n"

	exit 2
fi

echo -ne " success!\n"\
" Updating file ownership and permissions of $FILESCHEDMAN..."

chown 0:0 $DESTINATIONMAN/$FILESCHEDMAN
chmod 744 $DESTINATIONMAN/$FILESCHEDMAN

echo -ne " success!\n\n"\
" Installation of NSAFlood finished successfully.\n\n"

exit 0
