.TH NSAFLOOD 1 "09/19/2014" "1.0"
.SH NAME
nsaflood \- Flood the Internet with encrypted data
.SH SYNOPSIS
.B nsaflood
[\fIoptions\fP]
.SH DECRIPTION
.B NSAFlood
creates a file of junk data, encrypts it, and transmits it across networked computers. NSAFlood was made specifically to combat Internet surveillance, by transmitting large amounts of encrypted data across the Internet, which the United States National Security Agency (NSA) must copy and store in its entirety, indefinitely, as is their policy for all encrypted Internet traffic.

It is recommended that you schedule nsaflood to run periodically through the crontab.
.SH OPTIONS
.TP

.BR \-h\ \fIhost\fR ", " \-\-host\ \fIhost\fR
	IP address or URL of target machine.

.TP
.BR \-s\ \fIsize\fR ", " \-\-file-size\ \fIsize\fR
	Size of the file to be transmitted, measured in Megabytes. 

.TP
.BR \-b\ \fIKilobits/s\fR ", " \-\-bandwidth\ \fIKilobits/s\fR
	Limit the bandwidth used by the program. Default is 
	512 Kilobits/second. Measured by Kilobits/S.

.TP
.BR \-g ", " \-\-garbage-file\fR
	The garbagefile to be transfered to the next host.

.TP
.BR \-t ", " \-\-ttl\fR
	The TTL of the current garbagefile.

.TP
.BR \-S ", " \-\-start\-server\fR
	Start the listening server.

.TP
.BR \-\-version\fR
	Get the version and copyright information of NSAFlood.

.TP
.BR \-h ", " \-\-help\fR
	Get usage information for NSAFlood.
