.TH NSAF-SCHED 1 "06/18/2014" "1.3.2"
.SH NAME
nsaf-sched \- Schedule NSAFlood
.SH SYNOPSIS
.B nsaf-sched
[\fI--list\fP | \fI--delete\fP | \fIoptions\fP]
.SH DECRIPTION
.B nsaf-sched
schedules NSAFlood, which creates a file of junk data read from /dev/urandom, and transmits it across networked computers. Use nsaf-sched to run NSAFlood automatically over certain periods.

It is recommended that you schedule NSAFlood to run sometime between midnight and early morning, as many ISPs do not count Internet traffic during this time against your data cap. To find out if your ISP has this policy you should visit their website.
.SH OPTIONS
.TP

.BR \-l ", " \-\-list\fR [\fIoptions\fP]
	List all nsaflood cronjobs. Arguments can be specified 
	to limit the number of jobs selected for possible deletion.

.TP
.BR \-dl\ \fIline\fR ", " \-\-delete\ \fIline\fR
	Delete the nsaflood job on the specified line number. Use
	--list to get a list of all nsaflood jobs in the crontab
	and their line numbers.
.TP
.BR \-u\ \fIUser\fR ", " \-\-user\ \fIUser\fR
	The user you wish nsaflood to be run as. By default is 
	equal to current user.

.TP
.BR \-m\ \fIminute\fR ", " \-\-minute\ \fIminute\fR
	The minute (0-50) for the command to run at.

.TP
.BR \-hr\ \fIhour\fR ", " \-\-hour\ \fIhour\fR
	The hour (0-23) for the command to run at.

.TP
.BR \-D\ \fIday\fR ", " \-\-day\ \fIday\fR
	The day (1-31) for the command to run on.

.TP
.BR \-M\ \fImonth\fR ", " \-\-month\ \fImonth\fR
	The month (1-12) for the command to run on.

.TP
.BR \-d\ \fIday\fR ", " \-\-week-day\ \fIday\fR
	The week day (0-6) for the command to run on.

.TP
.BR \-b\ \fIKilobits/s\fR ", " \-\-bandwidth\ \fIKilobits/s\fR
	Limit the bandwidth used by the nsaflood. Default is 
	2048 Kilobits/second. Measured by Kilobits/S.

	Limit jobs selected as candidates for deletion to the 
	specified bandwidth setting.

.TP
.BR \-h\ \fIuser@host\fR ", " \-\-host\ \fIuser@host\fR
	Username and IP address of target machine.

	Limit jobs selected as candidates for deletion to the 
	specified user@host.

.TP
.BR \-k\ \fIkeyfile\fR ", " \-\-key-file\ \fIkeyfile\fR
	Key which may be used to connect to the host in place of a 
	password

	Limit jobs selected as candidates for deletion to the 
	specified keyfile.

.TP
.BR \-s\ \fIsize\fR ", " \-\-file-size\ \fIsize\fR
	Size of the file to be transmitted, measured in Megabytes. 

	Limit jobs selected as candidates for deletion to the 
	specified file size.

.TP
.BR \-V ", " \-\-version\fR
	Get the version and copyright information of nsaf-sched.

.TP
.BR \-h ", " \-\-help\fR
	Get usage information for nsaf-sched.

.SH EXIT STATUS
The program will return 0 if it is successfull. If the user did not supply the necessary arguments, the return code will be 1. If the user supplies a bogus argument, the return code will be 2. If the user is not root, it will return 3.
